# worlds/wow/ExportLua.py
import os
import json

def export_lua_config(export_path, options):

    EXPORT_PATH = os.path.join(export_path, "AP_Config.lua")
    print(options)
    # --- Generate Lua tables ---
    lines = ["-- Auto-generated by ExportLuaConfig.py", ""]

    lines.append("settings = {")
    lines.append(f"    starting_zone: {options.starting_zone.value},")
    lines.append(f"    speed: {options.speed_boost.value},")
    lines.append(f"    exp_rate: {options.exp_boost.value},")
    lines.append(f"    heirloom_armor: {options.heirloom_armor.value},")
    lines.append(f"    heirloom_weapons: {options.heirloom_weapons.value},")
    lines.append(f"    heirloom_trinkets: {options.heirloom_trinkets.value},")
    lines.append(f"    starting_inventory: 0,") # Not implemented
    lines.append("}")

    with open(EXPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[ExportLuaSettings] Export complete -> {EXPORT_PATH}")
