# worlds/wow/ExportLua.py
import os
import json

def export_lua_mappings(export_path, quest_data, zones, spell_data, item_table, location_table, spells_mapping):

    EXPORT_PATH_LOC = os.path.join(export_path, "AP_LocationIds.lua")
    EXPORT_PATH_ITM = os.path.join(export_path, "AP_ItemIds.lua")

    # --- Generate Lua tables ---
    lines = ["-- Auto-generated by ExportLua.py", "AP_LocationIds = {"]

    # Write AP_LocationIds
    for name, loc_id in location_table.items():
        # Include both quests/spells and levels
        lines.append(f"    [\"{name.replace("\"", "")}\"] = {loc_id},")
    lines.append("}")

    # Level > Location ID mapping
    lines.append("-- Map levels > Archipelago location IDs")
    lines.append("-- (Some item ids are created in between the first levels and Final Level)")

    lines.append("level_to_location = {")
    for lvl in range(2, 81):
        name = f"Level {lvl}"
        if name in location_table:
            lines.append(f"    [{location_table[name]}] = \"{name}\",")
    lines.append("}")

    # Map WoW quest IDs -> AP location name
    lines.append("AP_QuestToLocation = {")

    for name in quest_data:
        quest_id = quest_data[name]['ID']
        lines.append(f'    [{quest_id}] = "{name}",')
    lines.append("}\n")

    # Map WoW spell IDs -> AP location name
    lines.append("AP_SpellToLocation = {")

    for name in spell_data:
        spell_id = spell_data[name]['id']
        lines.append(f'    [{spell_id}] = "{name}",')
    lines.append("}")

    with open(EXPORT_PATH_LOC, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[ExportLua] Export complete -> {EXPORT_PATH_LOC}")

    # --- Generate Lua tables ---
    lines = ["-- Auto-generated by ExportLua.py", "AP_ItemIds = {"]

    for name, data in spell_data.items():
        if name in item_table:
            lines.append(f'    ["{name}"] = {data["id"]},')

    for zone in zones.keys():
        if zone != "Timbermaw Hold" and zone != "Plaguelands: The Scarlet Enclave": # the former is not a real zone, the later is not yet implemented
            lines.append(f'    ["{zone}"] = {zones[zone]["id"]},')
    lines.append("}\n")

    # --- Generate Lua tables ---
    lines.append("AP_ItemNames = {")

    for name, data in spell_data.items():
        if name in item_table:
            lines.append(f'    [{data["id"]}] = "{name}",')

    for zone in zones.keys():
        if zone != "Timbermaw Hold" and zone != "Plaguelands: The Scarlet Enclave":
            lines.append(f'    [{zones[zone]["id"]}] = "{zone}",')
    lines.append("}\n")

    # --- Generate Lua tables ---
    lines.append("AP_ItemID_to_Name = {")

    for name, data in spell_data.items():
        if name in item_table:
            archId = item_table[name]
            lines.append(f'    [{archId}] = "{name}",')

    for zone in zones:
        name = f'Unlock {zone}'
        if name in item_table:
            archId = item_table[name]
            lines.append(f'    [{archId}] = "{name}",')
    lines.append("}\n")

    # --- Generate default data ---
    for className, data in spells_mapping.items():
        lines.append("SPELL_LIST_" + className.upper() + " = {")
        for spellName, spellData in data.items():

            if spellData["money_cost"] > 0 and spellData["Level"] > 0:
                lines.append("    {" + str(spellData["id"]) + ", " + str(spellData["money_cost"]) + ", " + str(spellData["Level"]) + ", \"" + spellName + "\"},")
        lines.append("}\n")

    with open(EXPORT_PATH_ITM, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
