# worlds/wow/ExportLua.py
import os
import json
import importlib.resources as pkg_resources


def export_lua_config(export_path, options, character_list):

    EXPORT_PATH = os.path.join(export_path, "AP_Config.lua")

    # --- Generate Lua tables ---
    lines = ["-- Auto-generated by ExportLuaConfig.py", ""]

    wowap_file = pkg_resources.files(__package__).joinpath("wowap.json")

    with wowap_file.open("r", encoding="utf-8") as f:
        zones = json.load(f)

    starting_zones = []
    for character in character_list:
        if character["starting_zone"] not in starting_zones:
            starting_zones.append(zones[character["starting_zone"]]['id'])

    string_list = str(starting_zones).replace("[", "{").replace("]", "}")

    lines.append("settings = {")
    lines.append(f"    [\"starting_zones\"] = {string_list},")
    lines.append(f"    [\"speed\"] = {options.speed_boost.value},")
    lines.append(f"    [\"exp_rate\"] = {options.exp_boost.value},")
    lines.append(f"    [\"heirloom_armor\"] = {options.heirloom_armor.value},")
    lines.append(f"    [\"heirloom_weapons\"] = {options.heirloom_weapons.value},")
    lines.append(f"    [\"heirloom_trinkets\"] = {options.heirloom_trinkets.value},")
    lines.append(f"    [\"riding_level\"] = 0,") # Not implemented
    lines.append(f"    [\"starting_inventory\"] = 0,") # Not implemented
    lines.append(f"    [\"starting_spells\"] = 0,") # Not implemented
    lines.append("}")

    with open(EXPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[ExportLuaSettings] Export complete -> {EXPORT_PATH}")
