# worlds/wow/ExportLua.py
import os
import json

def export_lua_config(export_path, options):

    EXPORT_PATH = os.path.join(export_path, "AP_Config.lua")
    print(options)
    # --- Generate Lua tables ---
    lines = ["-- Auto-generated by ExportLua.py", ""]

    lines.append("settings = {")
    lines.append("    speed: 1,")
    lines.append("    exp_rate: 1,")
    lines.append("}")

    with open(EXPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[ExportLuaSettings] Export complete -> {EXPORT_PATH}")
